name: forc-node sanity

on:
  push:
    branches:
      - "**"
  pull_request:

jobs:
  linux:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Nix
        uses: cachix/install-nix-action@v27
        with:
          extra_nix_config: |
            substituters = https://cache.nixos.org https://fuellabs.cachix.org
            trusted-public-keys = cache.nixos.org-1:6NCHdD59X431o0gWypbMrAURkbJ16ZPMQFGspcD7cjw= fuellabs.cachix.org-1:qcA4niPC7ub2V6lYkN0gqQTQW85UYjJgRHaN8hSMKps=
      - name: Build forc-node (Linux)
        run: nix build --print-build-logs --no-update-lock-file .#forc-node-0.69.2

  macos:
    runs-on: macos-14
    steps:
      - uses: actions/checkout@v4
      - name: Set up Nix
        uses: cachix/install-nix-action@v27
        with:
          extra_nix_config: |
            substituters = https://cache.nixos.org https://fuellabs.cachix.org
            trusted-public-keys = cache.nixos.org-1:6NCHdD59X431o0gWypbMrAURkbJ16ZPMQFGspcD7cjw= fuellabs.cachix.org-1:qcA4niPC7ub2V6lYkN0gqQTQW85UYjJgRHaN8hSMKps=
      - name: Build forc-node (macOS)
        run: nix build --print-build-logs --no-update-lock-file .#forc-node-0.69.2
